#!/system/bin/sh
echo "=============================================="
echo " PICO 4 Motion Tracker Unlock (2.0.5) v2.7"
echo " Single build | STOCK scheduling (as-is)"
echo "=============================================="
echo "This module does NOT switch algorithms and does"
echo "NOT tune CPU/GPU - it runs the STOCK app with"
echo "STOCK scheduling (BODYPOSE 1.0.0.47)."
echo "Fixes: tracker detection + install/upgrade/uninstall."
echo "Performance tuning now lives in pico4-power-mode."
echo ""
echo "[RU] Единая сборка: стоковое приложение и стоковый"
echo "     алгоритм, без настройки CPU. Тюнинг — в pico4-power-mode."
echo ""
echo "[ZH] 单档版：原版应用 + 原厂调度（不做性能调优）。"
echo "     性能调优已迁移至 pico4-power-mode 项目。"
echo "=============================================="
exit 0
