#!/system/bin/sh
echo "=============================================="
echo " PICO 4 Motion Tracker Unlock (2.0.5) v2.6"
echo " Standard | STOCK algorithm (use as-is)"
echo "=============================================="
echo "This module does NOT switch algorithms."
echo "It enables the STOCK app + STOCK algorithm (BODYPOSE 1.0.0.47)."
echo "Fixes: tracker detection + install/upgrade/uninstall lifecycle."
echo ""
echo "[RU] Стандартная версия. Используется стоковое приложение"
echo "     и стоковый алгоритм. Переключение алгоритмов не требуется."
echo ""
echo "[ZH] 标准版：原版应用 + 原版算法，无需切换。"
echo "=============================================="
exit 0
